# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d406110ef4227a8cea01ab5f201293fe3952824fa793eaf8f8e2c210877294776599e5a23ce705ed4475fdfe4c50a9721b67a213ec1c26d4530f2b1aa0214ed0

test:
  secret_key_base: 8c9d0c61271743249017e0a33a6ce446e64aa4042745280fcc7a119544a26ce9f43efbb849104043a72918489ed6465173b4b41c9f40318bcc63585446b6633e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
